name: carsonsale
description: "CarOnSale Flutter Coding Challenge"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.0.0
  build_runner: ^2.4.15
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  freezed: ^3.0.2
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  hive: ^2.2.3
  http: ^1.3.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true
